### PR TITLE
Table of contents and moving the 'what you built' section to the bottom of the chapter

### LINKED ISSUE #6: Rename Chapters to Actions rather Than Concepts
@oren  suggested that Titles should reflect what we are doing rather than concepts we haven't covered yet. 

The titles for Chapters 3 through 6 will need to be changed to reflect that.

### PR DESCRIPTION
**Pull request by oren**
This is another suggestion - table of contents. I used this tool to generate it: https://github.com/ekalinin/github-markdown-toc

In addition I moved the 'all the code' section to the bottom. Just to play with it and see if it looks good.

### CODE REVIEW

**Comment by oren** [comment]
I created a separate branch since i didn't want to have this commit as part of the same PR. That didn't work (:

**Comment by oren** [comment]
You can see it on my branch - https://github.com/oren/learn-to-code-rust-baseball/blob/ee67fb1d2c158683ccd42dd9ed47b7536f02e599/articles/04%20-%20De-Serialization.md

**Comment by oren** [comment]
Here it is including numbers for headers - https://github.com/oren/learn-to-code-rust-baseball/blob/3a85239e12d1d2e9dfff109aee42612e1916fd26/articles/04%20-%20De-Serialization.md

**Review by elibenporat — DISMISSED** [review]

**Comment by elibenporat** [comment]
I really like how the "all the code of this chapter" work, it's really great on many levels. I can't figure out how to merge just that, and not the TOC as well.

The target audience is going to be FanGraphs readers (I've been writing for their THT arm for 4 years). Once this is complete, the plan is to publish it there, so I'm not sold on a Table Of Contents for now, as I think it makes the overall feel more textbook-y and less inviting. My plan is to make this into an MdBook as well, so would want to conform to this style: https://doc.rust-lang.org/book/ch01-01-installation.html

**Comment by elibenporat** [comment]
Still learning GitHub. Would love a PR with just the "All the Code of This Chapter", for any chapters that you want attribution for. Still new to GitHub/open source etc, so apologies if I've sent you too many notifications / duplications.

Appct your interest in this project, I'm really hoping this will make Rust more inviting for a lot of people who are net-new to the programming world. The "All the Code" section will make this a lot more accessible for everyone.

**Comment by oren** [comment]
I know other languages btw so i am not the target audience but I find this tutorial helpful. The reason I like it is it's not teaching me the technical aspects of the language one after the other like 99% of the books out there. I find this approach boring. Instead what I like to see is a guide/book/tutorial that build an app and each chapter is focused on the feature of the app, and not the feature of the language. It's hard because it means that some features of the language will not be presented or maybe some features will be repeated but it's more **fun** and more importantly it's **mimics the way you build a software product**.

**Comment by oren** [comment]
Also it will be more appealing to engineers who cares about building products more than the technical aspects of the language. At least that's the case for me.

**Comment by elibenporat** [comment]
> I know other languages btw so i am not the target audience but I find this tutorial helpful. The reason I like it is it's not teaching me the technical aspects of the language one after the other like 99% of the books out there. I find this approach boring. Instead what I like to see is a guide/book/tutorial that build an app and each chapter is focused on the feature of the app, and not the feature of the language. It's hard because it means that some features of the language will not be presented or maybe some features will be repeated but it's more **fun** and more importantly it's **mimics the way you build a software product**.

This is great to hear, as it is exactly what I'm aiming for. I'm very keen on only explaining technical aspects of the language that are directly relevant to each part. My goal is to move the code in a direction that allows me to show the Rust perspective on it, as we go.

**Comment by oren** [comment]
And that's why I like the titles of chapter 2 and 3 more than 4 and 5. The titles of 2 and 3 are related to the product I am building (basic baseball app, showing player info) while 4 and 5 are about features of Rust (de-serialization, enums, structs).

**Comment by elibenporat** [comment]
That's a very good point. I'll think of better titles. Pedantically, (de)serialization is a general concept, but your point still stands and they should be internally consistent. Will probably change this to "Downloading Data" and "Describing Data" or something along those lines. Open to suggestions.

**Comment by oren** [comment]
What you can do is explaining at the beginning of each chapter what
technical concepts are you teaching me - structs, serialization etc. And if
you want to be even more hardcore you should try to use verbs that describe
learning such as: understand xxx, apply usage of xxx, be able to compare
xxx, etc. I am on my mobile but will share a link soon to a website about
this.

**Comment by oren** [comment]
https://tips.uark.edu/blooms-taxonomy-verb-chart/

**Pull request closed without merging**
