### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by oren**

### CODE REVIEW

**Comment by oren** [comment]
This is just a suggestion. As a student, I learn faster by first building something and than understanding how I built it. Feel free to ignore this PR if you don't agree with this approach.

**Comment by elibenporat** [comment]
You're pedagogical approach has a lot of merit and is related to some feedback I received from one of my (offline) beta-testers. He was looking for a "this is what you should see" at the **end** of each chapter.

Keep in mind that my target audience, is someone without any coding experience at all. Given that target, my strong preference would be to have bulky code sections at the end, rather than at the beginning, so as not to overwhelm the learner.

Let me know your thoughts. Happy to merge this, but would move it down to the end, with a shortcut link at the top. I've been sorta-kinda doing this by pushing the main.rs file the end of each chapter to the /src directory, but this approach is definitely superior.

**Comment by oren** [comment]
Make sense to put it at the end. Go for it!

**Review by elibenporat — APPROVED** [review]

**Review by elibenporat — COMMENTED** [review]
This looks great! Going to merge this and then move it to the bottom.

**Comment by elibenporat** [comment]
Looks like my github skills are quite lacking and I only merged the typo fix? Can you submit another PR with the "All the Code in This Chapter Section"? I'm happy to copy-paste it in, but prefer to have the github history act as attribution.

**Comment by oren** [comment]
Don't worry about it....just change it yourself (:

**Comment by elibenporat** [comment]
Never mind, it did merge in. Fixed it up and moved it around. Thanks again, this is a great addition.

**Pull request merged**
